# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-Grepl
version:      0.01
version_from: lib/App/Grepl.pm
installdirs:  site
requires:
    File::Next:                    0.4
    PPI:                           1.118
    Scalar::Util:                  1.19
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
